apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-node-affinity-deployment-cicd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: with-node-affinity-cicd
  template:
    metadata:
      labels:
        app: with-node-affinity-cicd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/nodegroup
                    operator: In
                    values:
                      - mngn-default-2024092509341828670000000d
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "gpuGroup"
          effect: "NoSchedule"
      containers:
        - name: with-node-affinity
          image: 437291019013.dkr.ecr.eu-central-1.amazonaws.com/infra/toolbox:python3.9.18-aws-cli # registry.k8s.io/pause:2.0
          resources:
            requests:
              memory: "4G"
              cpu: "3"
            limits:
              memory: "4G"
              cpu: "3"
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: with-node-affinity
#  namespace: actions-runner-system
#spec:
#  affinity:
#    nodeAffinity:
#      preferredDuringSchedulingIgnoredDuringExecution:
#        - weight: 1
#          preference:
#            matchExpressions:
#              - key: app
#                operator: In
#                values:
#                  - jenkins
#  tolerations:
#    - key: "worker-group"
#      operator: "Equal"
#      value: "cicd"
#      effect: "NoSchedule"
#  containers:
#    - name: with-node-affinity
#      image: registry.k8s.io/pause:2.0
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: with-node-affinity
#spec:
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: topology.kubernetes.io/zone
#                operator: In
#                values:
#                  - antarctica-east1
#                  - antarctica-west1
#      preferredDuringSchedulingIgnoredDuringExecution:
#        - weight: 1
#          preference:
#            matchExpressions:
#              - key: another-node-label-key
#                operator: In
#                values:
#                  - another-node-label-value
#  containers:
#    - name: with-node-affinity
#      image: registry.k8s.io/pause:2.0