apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/lifecycle
            operator: In
            values:
            - normal
  containers:
    - name: with-node-affinity
      image: registry.k8s.io/pause:2.0
      resources:
        limits:
          cpu: 64m
          memory: 64Mi
        requests:
          cpu: 64m
          memory: 64Mi